feat: Complete the implementation of the  latest APIs.
casbin-net/efcore-adapter pull request #63
Opened 2022-08-20 13:20 UTC by AsakusaRinne

Sync with the latest APIs of ```Casbin.NET 2.x```.

2022-08-20 13:23 UTC, hsluoyz commented
@sagilio plz review

2022-08-20 22:15 UTC, sagilio requested changes
Most LGTM

2022-08-20 22:15 UTC, sagilio commented on Casbin.Adapter.EFCore/Extensions/CasbinRuleExtenstion.cs
> +        internal static void SetValue(this ICasbinRule rule, IPolicyValues values)
```suggestion
        internal static void SetValues(this ICasbinRule rule, IPolicyValues values)
```

2022-08-20 22:15 UTC, sagilio commented on Casbin.Adapter.EFCore/Extensions/CasbinRuleExtenstion.cs
> +        internal static TCasbinRule Parse<TCasbinRule>(string policyType, IPolicyValues ruleStrings)
```suggestion
        internal static TCasbinRule Parse<TCasbinRule>(string policyType, IPolicyValues values)
```

2022-08-20 22:15 UTC, sagilio commented on Casbin.Adapter.EFCore/EFCoreAdapter.cs
> +                UpdatePolicyAsync(section, policyType, oldRules[i], newRules[i]);
```suggestion
                await UpdatePolicyAsync(section, policyType, oldRules[i], newRules[i]);
```

2022-08-21 14:30 UTC, hsluoyz commented
@sagilio

2022-08-22 05:45 UTC, sagilio approved these changes
LGTM

2022-08-22 05:46 UTC, sagilio commented
@AsakusaRinne plz sign off the commits 
![image](https://user-images.githubusercontent.com/42855245/185847889-22409e39-fba0-43b3-b273-28edc3fef6b5.png)

2022-08-22 06:52 UTC, AsakusaRinne commented
> @AsakusaRinne plz sign off the commits ![image](https://user-images.githubusercontent.com/42855245/185847889-22409e39-fba0-43b3-b273-28edc3fef6b5.png)

OK, done.

2022-08-22 06:56 UTC, merged